server:
  port: 22977

spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://pg:5432/studs
    username: s244709
    password: bgi855

  jpa:
    hibernate:
      ddl-auto: none
