server:
  port: 22977

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://pg:5432/studs
    username: s244709
    password: bgi855

  jpa:
    hibernate:
      ddl-auto: create-drop
